// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package di

import (
	"backend/model"
)

// Injectors from wire.go:

func InitializeEvent() model.Event {
	message := model.NewMessage()
	greeter := model.NewGreeter(message)
	event := model.NewEvent(greeter)
	return event
}

func InitializeGreeter() model.Greeter {
	message := model.NewMessage()
	greeter := model.NewGreeter(message)
	return greeter
}
